  enum = ["INITIATED","NOT_INITIATED","WAITING_FOR_APPROVAL_FROM_RESTAURANT","WAITING_FOR_DELIVERY_PARTNER","PLACED","PICKUP_BY_DELIVERY_PARTNER","DELIVERED","READY_TO_PICKUP"]

[id]
  type = "Number"

[fromRestaurant]
  type = "Number"

[orderStatus]
  type = "String"

[placedAt]
  type = "Date"

[fulfilledAt]
  type = "Date"

[orderItems]
  type = "Object"

